### PR TITLE
Improve flatdata-inspector

### PR DESCRIPTION
**Pull request by VeaaC**
* Do not copy memory when slicing RawData (massive speed gain on some scenarios)
* Support slicing Multivector
* Fix out-of-bounds for Multivector's len()
* add helper functions to extract strings from RawData, as well as string lists and fixed sized arrays
* Downgrade CI image since `nose` is not working with Python 3.10
* Simplify TAR backend a bit by also using memoryview

### CODE REVIEW

File: .github/workflows/generator.yml [hunk 1]
```diff
@@ -11,7 +11,7 @@ env:
 
 jobs:
   Build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
```
Comment (eikesr) [inline .github/workflows/generator.yml:14]: Why not 22.04?

File: flatdata-py/flatdata/lib/resources.py [hunk 2]
```diff
@@ -171,6 +188,32 @@ def __getitem__(self, item):
             ]
         return self._mem[item + SIZE_OFFSET_IN_BYTES:item + SIZE_OFFSET_IN_BYTES + 1]
 
+    def sub_str(self, index, separator = b'\0'):
+        for i in range(index, len(self)):
+            if all(a == b for (a, b) in zip(self[i:], separator)):
```
Comment (eikesr) [inline flatdata-py/flatdata/lib/resources.py:193]: Is `self[i:]` not a byte-string? I would find using `startswith` more readable, e.g.:

```
b'abc\0\0def'[3:].startswith(b'\0\0')
```

Or even scrap the loop and use `find`?

File: .github/workflows/generator.yml (hunk 1 above)
Comment (VeaaC) [reply .github/workflows/generator.yml:14]: 22.04 Has Python 3.10, and our current unit test framework (nose) does not work with Python 3.10 :-(

File: flatdata-py/flatdata/lib/resources.py (hunk 2 above)
Comment (VeaaC) [reply flatdata-py/flatdata/lib/resources.py:193]: It is `bytes`, not a string. How would a version of `find` that gives me an index look like?

Comment (eikesr) [reply flatdata-py/flatdata/lib/resources.py:193]: https://docs.python.org/3/library/stdtypes.html#bytes.find would work? Although you need to check for `-1` as a return value in case the substring was not found

```
separator_index = self.find(separator, start=index)
# or
separator_index = self[index:].find(separator)
# then
if separator_index == -1:
  return bytes(self[index]).decode("utf-8")
return bytes(self[index:separator_index).decode("utf-8")
```

Comment (VeaaC) [reply flatdata-py/flatdata/lib/resources.py:193]: `AttributeError: 'memoryview' object has no attribute 'find'`

And converting to `bytes` reads all the data into memory

Comment (eikesr) [reply flatdata-py/flatdata/lib/resources.py:193]: Hmm, still find the zip solution a bit obscure, but I guess there is now easy way around it

**Review by eikesr — APPROVED** [review]

**Comment by VeaaC** [comment]
Agree, but I could not find anything easy to use... I am not expert in Python, though
